# Generated by Django 4.1.13 on 2024-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalavail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('availability', models.CharField(max_length=50, null=True)),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
