# Generated by Django 4.1.13 on 2024-07-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multihospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalavail',
            name='availabilitylist',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('blood', 'Blood'), ('organ', 'Organ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospitalavail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
