# Generated by Django 4.1.13 on 2024-07-30 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multihospital_app', '0005_hospitaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
