# Generated by Django 4.1.13 on 2024-08-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multihospital_app', '0006_alter_hospitaldetail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaldetail',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospitaldetail',
            old_name='address_line_2',
            new_name='landmark',
        ),
    ]
